language: node_js

node_js: 
  - "15.4.0"

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - gibrandev80@gmail.com
  slack: sangalletano:eS4cQisa4rZ9tkpWcvQoDCHz

git:
  depth: 3

script: 
  - yarn build 

deploy: 
  provider: pages
  skip_cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  local_dir: .next/
  target_branch: gh-pages
  commit_message: "Deploy of the project"
  on:
    branch: master

